version: '3.7'
services:
  db:
    image: 'mongo'
    ports:
      - 27017:27017
  app:
    image: 'ruby:2.7.0'
    build: .
    command: bundle exec shotgun ./api.rb --port=5000 --host="0.0.0.0"
    ports:
      - 5000:5000
    volumes:
      - '.:/test'
